messages:
  prefix: "&b&lKỹ Năng &r&7» "
  reload: "&aĐã tải lại cấu hình Kỹ Năng thành công!"
  no_permission: "&cBạn không có quyền để làm điều này."
  player_only: "&cChỉ người chơi mới có thể dùng lệnh này."
  skill_not_found: "&cKhông tìm thấy kỹ năng nào có tên lệnh là '&e{skill}&c'."
  on_cooldown: "&cKỹ năng &e{skill_name} &cđang trong thời gian hồi. Vui lòng chờ &e{time} &cgiây."
  not_enough_mana: "&cKhông đủ năng lượng! Cần &e{mana_cost} &cnăng lượng (level), bạn chỉ có &e{current_mana}&c."
  skill_list_header: "&f--- &a&lDanh sách Kỹ năng của bạn &f---"
  skill_list_entry: "&e/skill {command} &7- &f{name} &7(Năng lượng: {mana}, Hồi chiêu: {cooldown}s)"
  help_header: "&f--- &b&lTrợ giúp SkillMC &f---"
  help_list: "&a/skillmc list &7- Liệt kê các kỹ năng bạn có thể dùng."
  help_reload: "&c/skillmc reload &7- Tải lại cấu hình (chỉ admin)."
  help_use: "&a/skill <tên_lệnh> &7- Dùng một kỹ năng."