# Tên của quy trình build
name: Build SkillAnime Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- BẮT ĐẦU THAY ĐỔI ---
      - name: Set up JDK 21 # Đổi tên cho dễ đọc
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Thay đổi quan trọng nhất: từ '17' thành '21'
          distribution: 'temurin'
          cache: 'maven'
      # --- KẾT THÚC THAY ĐỔI ---

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkillAnime-Build-Java21 # Đổi tên để phân biệt
          path: target/*.jar